os: linux
dist: xenial

language: node_js

node_js:
    - 14

jobs:
  include:
    - stage: deploy docs
      script: npm run build-storybook
      deploy:
        provider: pages
        skip_cleanup: true
        token: $VUE_PDFJS_GITHUB_TRAVIS
        keep_history: true
        local_dir: dist/docs
        on:
          branch: main
